services:
  backend:
    build: ./Backend
    network_mode: "host"  # Uses host networking
    env_file: ./Backend/.env

  frontend:
    build: ./Frontend
    network_mode: "host"  # Uses host networking
    depends_on:
      - backend